### ISSUE TITLE
1- Please remove Test crash from Login screen (Screenshot Attached)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Primp-Blow#1]
![1- Please remove Test crash from Login screen (Screenshot Attached).jpg](https://images.zenhubusercontent.com/5ffeda0ad883b3ad5058dad4/9efe2a42-c205-40f2-9cb4-65e362aac9dd)

**Comment by MuhammadUsama155** [comment]
@Osama-123-dot  done.
