### ISSUE TITLE
10- In Book an Appointment, Service should be Services as per Marvel (Screenshot Attached)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Primp-Blow#10]
![10- In Book an Appointment, Service should be Services as per Marvel (Screenshot Attached).jpg](https://images.zenhubusercontent.com/5ffeda0ad883b3ad5058dad4/8c243b9f-8111-41fa-83cd-1fbd15f09d70)

**Comment by MuhammadUsama155** [comment]
done
