### ISSUE TITLE
12- In Membership screen, agree terms and condition line missing in the app as per Marvel (Screenshot Attached)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Primp-Blow#12]
![12- In Membership screen, agree terms and condition line missing in the app as per Marvel (Screenshot Attached).PNG](https://images.zenhubusercontent.com/5ffeda0ad883b3ad5058dad4/26aa4daa-f32f-4b03-9b21-5950b8b9cd45)

**Comment by MuhammadUsama155** [comment]
done
