### ISSUE TITLE
2- In Login screen, Please correct Remember me spelling (Screenshot Attached)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Primp-Blow#2]
![2- In Login screen, Please correct Remember me spelling (Screenshot Attached).jpg](https://images.zenhubusercontent.com/5ffeda0ad883b3ad5058dad4/24b20ec8-2fcc-471d-a719-d17543683898)

**Comment by MuhammadUsama155** [comment]
@Osama-123-dot done.
