### ISSUE TITLE
5- In Book an appointment screen, Blowout b should be capital (Screenshot Attached)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Primp-Blow#5]
![5- In Book an appointment screen, Blowout b should be capital (Screenshot Attached).jpg](https://images.zenhubusercontent.com/5ffeda0ad883b3ad5058dad4/d167738e-1a21-4172-8c2f-389a34370267)

**Comment by MuhammadUsama155** [comment]
done.
