### ISSUE TITLE
6- Book an Appointment missing in the app as per Marvel (Screenshot Attached)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Primp-Blow#6]
![6- Book an Appointment missing in the app as per Mervel (Screenshot Attached).jpg](https://images.zenhubusercontent.com/5ffeda0ad883b3ad5058dad4/1605f3dc-7b25-4048-bfbc-ac32b43e1e8b)

**Comment by MuhammadUsama155** [comment]
done
