### ISSUE TITLE
7- In Suggestion, Please remove all dummy text. Suggestion box should be empty (Screenshot Attached)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Primp-Blow#7]
![7- In Suggestion, Please remove all dummy text. Suggestion box should be empty (Screenshot Attached).jpg](https://images.zenhubusercontent.com/5ffeda0ad883b3ad5058dad4/5fc324dc-faf9-4a6b-b41a-dccffe174fd4)

**Comment by MuhammadUsama155** [comment]
done
