### ISSUE TITLE
8- Please change Continue text to Confirm as per Marvel (Screenshot Attached)

### ISSUE THREAD

**Issue by Osama-123-dot** [lntechadmin/Primp-Blow#8]
![8- Please change Continue text to Confirm as per Marvel (Screenshot Attached).jpg](https://images.zenhubusercontent.com/5ffeda0ad883b3ad5058dad4/73068b02-6dbf-44ac-a7f9-6fd15d1f2c90)

**Comment by MuhammadUsama155** [comment]
done
